### ISSUE TITLE
Страницы сводов. Интеграция

### ISSUE THREAD

**Issue by IlyaTheCreator** [woody-job/wood-client#16]
Необходимо интегрировать запросы для страниц сводов

**Comment by denischagin** [comment]
https://github.com/woody-job/wood-client/pull/48

**Comment by IlyaTheCreator** [comment]
* Лоадеры слишком большие на мой взгляд. Попробуй их сделать не по контейнеру санберста, а по нему самому.
* Отформатируй и пройдись линтером
* Нужно заюзать totalVolume из ответа, "Всего" захардкодено сейчас
