### ISSUE TITLE
Страницы поступлений/отгрузок. Интеграция

### ISSUE THREAD

**Issue by IlyaTheCreator** [woody-job/wood-client#18]
Необходимо интегрировать запросы для страниц поступлений/отгрузок

**Comment by denischagin** [comment]
https://github.com/woody-job/wood-client/pull/45

**Comment by IlyaTheCreator** [comment]
Замечания по #45 :

* В страницах для одного дня сделать по дефолту предыдущий день
* В страницах для диапазона дат сделать по дефолту позавчера - вчера
* В санберстах нужно отображать не проценты, а м3 (хотя может им и то, и то нужно будет, правится элементарно, наплевать)
* У "Всего из" добавить м3
* Проверить состояния полей форм при сохранении/повторном открытии. То placeholder слетает, то NaN проскакивает. Если поймешь, что много времени займет - можешь отложить это пока.
