### ISSUE TITLE
Страницы поступлений/отгрузок

### ISSUE THREAD

**Issue by IlyaTheCreator** [woody-job/wood-client#6]
Необходимо реализовать страницы поступлений и отгрузок, опираясь на схематическое описание https://excalidraw.com/#json=dc3mdh58k4nj_IQEEHKQ7,hbcrHcsz2_HX_riIy0zBTg

**Comment by IlyaTheCreator** [comment]
Update: см правки по crud операциям в таблицах

**Comment by denischagin** [comment]
https://github.com/woody-job/wood-client/pull/29
