### ISSUE TITLE
Раздел удаления всех данных о работе производства в настройках

### ISSUE THREAD

**Issue by IlyaTheCreator** [woody-job/wood-client#62]
Необходимо создать новый таб "стереть данные" в настройках системы с кнопкой "Удалить все данные о работе предприятия"

При нажатии на кнопку появляется первое диалоговое окно: 
Заголовок:
Удаление всех данных о работе предприятия

Содержание:
Следующие данные будут стерты из базы данных:
* Вход цехов
* Выход цехов
* Поступления
* Отгрузки
* Склад
* Ежедневные данные о работе цеха
* Созданные сушилки

Кнопки: продолжить/отмена

Если пользователь нажимает продолжить, открывается следующее модальное окно, с подтверждением по слову, как при удалении репозитория в гитхабе.
Заголовок: Удаление

Содержание:
Для удаления введите следующий текст: "удалитьнельзяпомиловать"

[инпут] - с валидацией по "удалитьнельзяпомиловать"

Кнопки удалить/отмета

**Comment by denischagin** [comment]
https://github.com/woody-job/wood-client/pull/73
