### ISSUE TITLE
Страница цеха

### ISSUE THREAD

**Issue by IlyaTheCreator** [woody-job/wood-client#7]
Необходимо реализовать страницу цеха, опираясь на схематическое описание https://excalidraw.com/#json=dc3mdh58k4nj_IQEEHKQ7,hbcrHcsz2_HX_riIy0zBTg

Замечание:
Второй цех не имеет информации о входе леса. Это нужно захардкодить и решить, как лучше отображать данные на страницы без этой таблицы.
(добавлять возможность для конфигурации этого момента я не вижу смысла. Цеха крайне статичны)

**Comment by IlyaTheCreator** [comment]
Update: см правки по crud операциям в таблицах

**Comment by denischagin** [comment]
https://github.com/woody-job/wood-client/pull/27
