### ISSUE TITLE
Страница сушилок

### ISSUE THREAD

**Issue by IlyaTheCreator** [woody-job/wood-client#8]
Необходимо реализовать страницу сушилок, опираясь на схематическое описание https://excalidraw.com/#json=dc3mdh58k4nj_IQEEHKQ7,hbcrHcsz2_HX_riIy0zBTg

Нужно учитывать, что сушилок будет 7. Нужно подумать, как правильнее их отобразить (возможно через табы)

**Comment by denischagin** [comment]
pr - https://github.com/woody-job/wood-client/pull/26
